### PR TITLE
add some european border crossing signs

### PR DESCRIPTION
**Pull request by mprins**
for the following countries:
- [x] at
- [x] be
- [ ] ~~ch~~
- [ ] ~~hr~~ not using
- [x] cz
- [x] de
- [x] dk
- [x] ee
- [x] es
- [x] fi
- [x] fr
- [x] gr
- [x] hu
- [ ] ~~ir~~
- [x] it
- [x] lu
- [x] nl
- [x] lt
- [x] lv
- [ ] ~~no~~ 
- [x] pl
- [x] se
- [x] si
- [x] sk
- [ ] ~~uk~~

### CODE REVIEW

**Comment by peterneubauer** [comment]
Man, you are getting good at SVGs!!!

**Comment by mprins** [comment]
it´s addictive :dizzy_face:

**Comment by mprins** [comment]
this: https://en.wikipedia.org/wiki/Comparison_of_European_road_signs was a great help in this

**Comment by peterneubauer** [comment]
With all the variations, there is some work left to cover everything :)

**Comment by d99m** [comment]
Thanks @mprins, amazing stuff!

**Pull request merged**
