### PR TITLE
Add danger_railway_crossing_secured and redraw triangle-shapes

### PR DESCRIPTION
**Pull request by floscher**
- Added a slider for adjusting the sign size to `sign-overview.html`
- Added sign `danger_railway_crossing_secured` (the unsecured one seems to differ between european countries, e.g. [Denmark](https://commons.wikimedia.org/wiki/File:Denmark_road_sign_A72.svg) and [Germany](https://commons.wikimedia.org/wiki/File:Zeichen_151.svg))
- Redrew triangle shapes. These are now vertically centered in the sense, that the padding is the same above and below. This is now used by some signs (see below).

Before/After:
before-after

### CODE REVIEW

**Comment by floscher** [comment]
@knikel the longer I work on this, the more I'm thinking that traffico should split europe.cson into files for individual countries, because there are several differences (some more subtle than others) between the European countries. E.g. the sign for unsecured railway crossings (see above), the signs with yellow background in Sweden [that you mentioned](https://github.com/mapillary/traffico/pull/4#issuecomment-73509234), different shades of red for the borders of the signs and most important signs with text in them…

Maybe the `europe.cson` could stay and serve as a fallback if this sign is not defined for the country, because it certainly would take much time until every single country has all the signs.

The changes I made are very much influenced by the German road signs as these are the ones I am most familiar with.

**Comment by jesolem** [comment]
Love this @floscher , awesome work!

**Comment by d99m** [comment]
@floscher Amazing stuff, thanks. You rock!

I really like the idea of having Europe as a fallback, totally agree with everything you've written. 
`europe.cson` - container for signs which are common in all European countries, specific country signs per file.
Unless we could assume that if a certain traffic sign is present in roughly the same form in ~15 countries, it lands in the `europe.cson`, what do you think @floscher?

Btw. Some shapes vary per country a bit, so I think, I would not go as far as creating e.g. 18 tractor shapes, for each country that has this sign, rather, I think we should have one common shape and then in case the shape is VERY different (not sure how to measure that though ;) ), the shape should be added per country. What's your take on that?

I've found this comparison http://en.wikipedia.org/wiki/Comparison_of_European_road_signs which I think we could use as a basis for adding further shapes/deciding what lands in the `europe.cson`.

**Comment by floscher** [comment]
> we could assume that if a certain traffic sign is present in roughly the same form in ~15 countries, it lands in the `europe.cson`, what do you think @floscher?

:+1:

> Btw. Some shapes vary per country a bit, so I think, I would not go as far as creating e.g. 18 tractor shapes, for each country that has this sign, rather, I think we should have one common shape and then in case the shape is VERY different (not sure how to measure that though ;) ), the shape should be added per country. What's your take on that?

Yes, 18 tractors are too many :wink:, one should do the job (at least at the current stage of the project). I wouldn't draw a clear line between country-specific signs and those for `europe.cson`. As a rough guide I'd prioritize the need for country-specific signs as follows, but this could vary from case to case:
- with text
- with different shapes (round vs. angular)
- with different colors (yellow background vs. white background)
- with different symbols (steam vs. electric train)
  <hr>
- with different shades of colors (bright red vs. muted red)
- with different sizing/spacing/weight (thicker borders, smaller symbol, …)
- with same symbol but different depictions (tractor 1 vs. tractor 2)

Those above the line should always be defined country-specific, the others should be discussed from case to case.

Maybe we could define colours and transformations per country. The country-specific cson-file could then contain an entry saying something like "this country has signXYZ from europe.cson with the colours and transformations for this country" (naturally with a proper syntax :wink:).
E.g. there could be a colour `danger_background` that would be white for Europe and yellow for Sweden. `se.cson` would then have an entry saying "Sweden has the sign danger_danger from europe.cson with Swedish colours".

> I've found this comparison http://en.wikipedia.org/wiki/Comparison_of_European_road_signs which I think we could use as a basis for adding further shapes/deciding what lands in the `europe.cson`.

Thanks, interesting, didn't know that. I previously only used the country-specific pages (linked at the bottom of http://en.wikipedia.org/wiki/Comparison_of_European_road_signs) in English and German.

By the way: It seems that Ireland mixes European signs and signs from the US.

**Pull request merged**
