### PR TITLE
Security fix for Travis build

### PR DESCRIPTION
**Pull request by floscher**
Previously commits with git tags were leaking the GitHub personal access token to the public when they were built on Travis CI.
This is now fixed by using a `~/.git-credentials`  file to store the access token (see https://www.kernel.org/pub/software/scm/git/docs/v1.7.9/gitcredentials.html for details).

The rest of the script that deploys the website should now also be more readable, as the gh-pages branch is now cloned into a separate directory instead of checked out in the same directory.

@knikel: The credentials are now stored in https://travis-ci.org/mapillary/traffico/settings as two environment variables `GH_USERNAME` and `GH_TOKEN`. Both can and should have the "display in logs"-switch flipped `OFF`.

Only the first commit contains the security fix, the other ones enhance other parts of the Travis build. I bundled them into one PR, but if only part of it should be merged, I'd happily split it up in more than one PR.

### CODE REVIEW

**Comment by floscher** [comment]
The new `.travis.yml` can be seen at work here: https://travis-ci.org/floscher/traffico/builds/97839607#L527
And here is the corresponding commit that is produced by it: https://github.com/floscher/traffico/commit/079bb98c1c8d4cea6ead12662ef10bb6e225321e

**Comment by floscher** [comment]
The four commits 98751e6827f21dffd8c8dd5f032f50aa5bef4636...e478c80586eed4cfbf5e607c59be2ffe39b63bc0 are for deploying the built files as ZIP via GitHub releases. See https://github.com/floscher/traffico/releases/tag/v0.1.20-pr.2 for how that would look.

**Comment by floscher** [comment]
And finally the last two commits e478c80586eed4cfbf5e607c59be2ffe39b63bc0...33f6539de0840809c98fa16795236616da118ed8 publish the unzipped release-zip to the [release-repo](https://github.com/mapillary/traffico-release). That should reduce the steps to release a new version to bumping the version number in `package.json` and tagging a commit in this repository with a git-tag.

As soon as this git-tag is pushed to GitHub, Travis will…:
- update traffico.io
- publish a release-zip via GitHub releases
- push the built files to https://github.com/traffico-release
- tag the new commit in the release-repo

See https://travis-ci.org/floscher/traffico/builds/97965606 for [.travis@`33f6539`](https://github.com/floscher/traffico/blob/33f6539de0840809c98fa16795236616da118ed8/.travis.yml) in action. And https://github.com/floscher/traffico-release/commit/f1a2d48a18f600b146c989cb308de8bd3c97e54d is the commit that it produces.

I think #33 is then fixed.

**Comment by d99m** [comment]
Thanks a lot @floscher!!

**Pull request merged**
