### PR TITLE
Added script that generates an HTML-overview of all signs

### PR DESCRIPTION
**Pull request by floscher**
This is intended as a replacement for the manually (?) created `dev/index.html`.

Everytime you run `gulp`, it generates an HTML-file containing all the signs defined in `build/*.json` and writes it to `build/signs.html`.

Each sign gets a slight shadow to stand out against the white background, which vanishes when hovering the sign (too see the "pure" sign without the shadow when needed).

The signs with variable content (currently speed, width and height limits) are rendered with different contents (adjustable in `scripts/generate-overview.js`).

This file can be viewed (at least) in Firefox and Chromium (previous `dev/index.html` didn't display the signs in Firefox).

See below for a preview how it looks like (click to enlarge):

sign_overview

### CODE REVIEW

**Comment by floscher** [comment]
e69565b introduced some changes to my first comment:
- The signs are now grouped not only by json-file, but also by category
- I've moved the generated json-files to build/json/*.json. I hope, that's ok.

See new screenshot below:
sign_overview_e69565b

**Comment by floscher** [comment]
Another update:
The script produces 4 files now:
- `build/sign-overview.html`: Standalone html-file for the developer to preview changes
- `build/stylesheets/examples.css`: used by `sign-overview.html` for styling
- `build/gh-pages/examples.html`: jekyll-html-file that can be directly transferred to the gh-pages-branch for publishing to traffico.io
- `build/gh-pages/examples.scss`: sass-fille that can be directly transferred to the gh-pages-branch (place it there as `_sass/pages/_examples.scss`)

And here is another preview, this time of how traffico.io/examples.html would look like (if #3 and #6 would also be merged):
examples

**Comment by d99m** [comment]
Amazing work @floscher, you rock! :metal: 
Thank you very much for all the contributions, I'm going through all your PRs right now!

**Comment by d99m** [comment]
Very cool idea with generating overview. I was meant to do it in the future.

Thanks a lot, you're awesome @floscher!

**Comment by floscher** [comment]
You're welcome. Great to see, that you like my contributions.

I'd like to start a `de.json`-file for German road signs. Should I duplicate the signs from `standard.json` into `de.json`, or should they appear only in one file? Most of the current signs in `standard.json` are used in Germany.

**Comment by d99m** [comment]
The thinking behind using `standard.json` was to keep all the european signs contained in it. So I think adding missing German signs to `standard.json` file is the way to go :+1: .

I think a good example of separating a country’s signs to a new file could be [Sweden](http://en.wikipedia.org/wiki/Road_signs_in_Sweden), where all the prohibitory and warning signs have yellow background.

**Comment by floscher** [comment]
OK, any objections to renaming `standard.json` to `europe.json`?
By the way: I just noticed, that http://traffico.io/shapes.html needs an update.

**Comment by d99m** [comment]
@floscher no objections whatsoever, that totally makes sense :+1:

Shapes are in sync with the latest build now.

**Comment by floscher** [comment]
Thanks, since 3e61968 the http://traffico.io/examples.html file is now out of sync (the standard traffic lights sign is without lights).

Seems like we need another script for automation :wink: (post-commit-hook or similar to move files to gh-pages-branch?).

**Pull request merged**
